# Generated by Django 3.2.16 on 2023-02-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=4096, verbose_name='push service url')),
                ('public_key', models.CharField(max_length=1024, verbose_name='subscriber public-key')),
                ('auth_key', models.CharField(max_length=1024, verbose_name='subscriber auth-key')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNSUBSCRIBED', 'Unsubscribed')], default='ACTIVE', max_length=255)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'ordering': ('-created_at',),
            },
        ),
    ]
